import { ArrowRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";

function Logo() { return <a href="/" className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#d4521a] text-lg font-bold text-white">P</span><span className="text-lg font-semibold tracking-tight text-[#2c211b]">Parlo</span></a>; }

const freeFeatures = ["2 active projects", "Client review portal", "File approvals and feedback", "Invoices via PayPal"];
const proFeatures = ["Unlimited active projects", "Branded client portals", "Priority workflow features", "Pro handoff pack", "Everything in Free"];

export default function PricingPage() {
  return <div className="min-h-screen bg-[#f5f0e8] text-[#2c211b]"><header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10"><Logo /><div className="flex items-center gap-2"><Button asChild variant="ghost"><a href="/login">Log in</a></Button><Button asChild className="bg-[#d4521a] text-white hover:bg-[#b94615]"><a href="/signup">Get started</a></Button></div></header><main className="mx-auto max-w-5xl px-5 pb-24 pt-16 sm:px-8 lg:pt-24"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#d4521a]">Simple pricing</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.05em]">Pick the plan that fits your week.</h1><p className="mt-5 text-lg leading-8 text-[#75675e]">Start free, then upgrade when Parlo becomes part of how you deliver.</p></div><div className="mx-auto mt-14 grid max-w-4xl gap-5 md:grid-cols-2"><article className="rounded-2xl border border-[#dfd0c4] bg-[#fbf7f1] p-7 sm:p-8"><div className="text-sm font-semibold text-[#8a776b]">Free</div><div className="mt-3 flex items-end gap-1"><span className="text-5xl font-semibold tracking-[-0.05em]">$0</span><span className="pb-1 text-sm text-[#8a776b]">forever</span></div><p className="mt-4 text-sm leading-6 text-[#75675e]">The essentials for getting a more professional client workflow.</p><Button asChild variant="outline" className="mt-7 w-full border-[#cdbbae] bg-transparent"><a href="/signup">Start free</a></Button><ul className="mt-8 space-y-3">{freeFeatures.map((feature) => <li key={feature} className="flex items-start gap-2 text-sm text-[#5f5148]"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#d4521a]" />{feature}</li>)}</ul></article><article className="relative rounded-2xl border-2 border-[#d4521a] bg-[#fffdfa] p-7 shadow-[0_20px_50px_rgba(212,82,26,0.13)] sm:p-8"><div className="absolute -top-3 left-7 rounded-full bg-[#d4521a] px-3 py-1 text-[11px] font-bold uppercase tracking-[0.12em] text-white">Most popular</div><div className="text-sm font-semibold text-[#d4521a]">Pro</div><div className="mt-3 flex items-end gap-1"><span className="text-5xl font-semibold tracking-[-0.05em]">$9</span><span className="pb-1 text-sm text-[#8a776b]">/ month</span></div><p className="mt-4 text-sm leading-6 text-[#75675e]">More room to grow, with the polished details clients notice.</p><Button asChild className="mt-7 w-full bg-[#d4521a] text-white hover:bg-[#b94615]"><a href="/signup">Start with Pro <ArrowRight className="ml-2 h-4 w-4" /></a></Button><ul className="mt-8 space-y-3">{proFeatures.map((feature) => <li key={feature} className="flex items-start gap-2 text-sm text-[#5f5148]"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#d4521a]" />{feature}</li>)}</ul></article></div></main></div>;
}
